version: '3.8'
services:
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
  server:
    image: app:latest
    command: air
    ports:
      - "3030:3030"
    depends_on:
      - db
    volumes:
      - .:/code
  client:
    image: app-client:latest
    command: npm run dev
    ports:
      - "8000:8000"
    depends_on:
      - server
    volumes:
      - .:/code