version: '3.8'
services:
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  server:
    build:
      context: ./app
    image: app:latest
    command: air
    ports:
      - "3030:3030"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app
  client:
    build:
      context: ./app-client
    image: app-client:latest
    command: npm run dev
    ports:
      - "8000:8000"
    depends_on:
      - server
    volumes:
      - ./app-client:/app
      - /app/node_modules